<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6fHWSIb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6fHWSIb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6fHWSIb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6fHWSIb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6fHWSIb\App_KernelDevDebugContainer([
    'container.build_hash' => '6fHWSIb',
    'container.build_id' => '27cb72b7',
    'container.build_time' => 1704227970,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6fHWSIb');
