<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGACCvwp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGACCvwp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGACCvwp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGACCvwp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGACCvwp\App_KernelDevDebugContainer([
    'container.build_hash' => 'GACCvwp',
    'container.build_id' => 'efe93fdd',
    'container.build_time' => 1701182507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGACCvwp');
