<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8JhT82S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8JhT82S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8JhT82S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8JhT82S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8JhT82S\App_KernelDevDebugContainer([
    'container.build_hash' => '8JhT82S',
    'container.build_id' => '6ef75a3d',
    'container.build_time' => 1701095959,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8JhT82S');
