security:

    #code ajouté pour la hiérarchie des roles
    #ROLE_SUPER_ADMIN a les droits de ROLE_ADMIN et ROLE_USER et ROLE_ADMIN a les droits de ROLE_USER.
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER]
        ROLE_ADMIN: ROLE_USER


    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\ConnexionAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/registration-event, roles: ROLE_USER }
        - { path: ^/gestionevent, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/insert-article, roles: ROLE_ADMIN }
        - { path: ^/insertcontact, roles: ROLE_ADMIN }
        - { path: ^/insertphone, roles: ROLE_ADMIN }
        - { path: ^/insertevent, roles: ROLE_ADMIN }
        - { path: ^/superadmin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/gestioncomment, roles: ROLE_SUPER_ADMIN }
        - { path: ^/gestion-centre, roles: ROLE_SUPER_ADMIN }
        - { path: ^/management-other-people-content, roles: ROLE_SUPER_ADMIN }
        - { path: ^/management-user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/visit, roles: ROLE_SUPER_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
